stages:
  - build_image
  - build_container


build_image:
  stage: build_image
  when: manual
  #allow_failure: false
  script:
  - echo "Login to Nexus Docker Registry"
  - echo "$NEXUS_PASSWORD" | docker login 192.168.0.112:8082 -u "admin" --password-stdin
  - bash ./nexus_image_push.sh "date_$(date '+%Y%m%d')" "$(git rev-parse HEAD | cut -c1-5)"

build_container:
  stage: build_container
  when: manual
  before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
   - ssh ubuntu@192.168.0.111 "DATE=date_$(date '+%Y%m%d') VERSION=$(git rev-parse HEAD | cut -c1-5) /home/ubuntu/website/docker-compose up -d"

