stages:
  - build_image

build_image:
  stage: build_image
  when: manual
  allow_failure: false
  before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
   - "ifconfig"
   - ssh ubuntu@192.168.0.111 "ifconfig"

