stages:
  - test
  - build_image
  - build_container1
  - build_container2

test:
  stage: build_image
  when: manual
  before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - ssh ubuntu@192.168.0.111
  script:
   - ifconfig
   - pwd
   - hostname

build_image:
  stage: build_image
  when: manual
  allow_failure: false
  script:
  - echo "Login to Nexus Docker Registry"
  - echo "$NEXUS_PASSWORD" | docker login 192.168.0.112:8082 -u "admin" --password-stdin
  - bash ./nexus_image_push.sh "d$(date '+%Y%m%d')" "$(git rev-parse HEAD | cut -c1-5)"

build_container1:
  stage: build_container1
  when: on_success
  before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
   - ssh ubuntu@192.168.0.111 "docker-compose down"
   - ssh ubuntu@192.168.0.111 "DATE=d$(date '+%Y%m%d') VERSION=$(git rev-parse HEAD | cut -c1-5) docker-compose up -d"
   - sleep 20

build_container2:
  stage: build_container2
  when: on_success
  before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
   - ssh ubuntu@192.168.0.113 "docker-compose down"
   - ssh ubuntu@192.168.0.113 "DATE=d$(date '+%Y%m%d') VERSION=$(git rev-parse HEAD | cut -c1-5) docker-compose up -d"
